"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type Dictionaries = Record<string, Record<string, any>>;
export type Locale = "en" | "zh" | "ru";

const dictionaries: Record<Locale, Record<string, any>> = {
  en: {
    menu: {
      products: "Products",
      solutions: "Solutions",
      projects: "Projects",
      support: "Lighting Resources",
      about: "About Us",
      contact: "Contact",
    },
    products: {
      wallWasher: "Wall Washer Light",
      linearLight: "Linear Light",
      projectorLight: "Projector Light",
      pointLight: "Point Light Source",
      corrugatedLight: "Corrugated Luminaire",
      columnLamp: "Column Lamp",
      windowSillLight: "Window Sill Light",
      stepLamp: "Step Lamp",
      wallLamp: "Wall Lamp",
      floodLight: "Flood Light",
      streetLight: "Street Light",
      solarLight: "Solar Light",
    },
    solutions: {
      roadStreet: "Road & Street Lighting",
      solar: "Solar Lighting Solution",
      landscape: "Landscape Lighting",
      facade: "Building Facade Lighting",
      industrial: "Industrial Lighting",
      gardenPark: "Garden & Park Lighting",
      stadiumArea: "Stadium & Area Lighting",
      urbanPublic: "Urban Public Lighting",
    },
    projects: {
      almatyMuseum: "Almaty Museum of Arts Facade Lighting",
      guangzhouDigitalCultureValley: "Guangzhou Digital Culture Valley Facade Lighting",
      road: "Road Lighting Project",
      plaza: "Commercial Plaza Lighting",
      landscape: "Landscape Park Lighting",
      facade: "Building Facade Lighting",
    },
    common: {
      home: "Home",
      productCenter: "Product Center",
      quickInquiry: "Quick Inquiry",
      search: "Search",
      language: "Language",
      exploreProducts: "Explore Products",
      viewProjects: "View Projects",
      sendInquiry: "Send Inquiry",
      viewProducts: "View Products",
      viewCase: "View Project",
      exploreSolution: "Explore Solution",
      location: "Location",
      usedProducts: "Used Products",
      backToProducts: "Back to Products",
      backToSolutions: "Back to Solutions",
      backToProjects: "Back to Projects",
      learnMore: "Learn More",
      searchResults: "Search products, solutions and projects",
      searchPlaceholder: "Type a keyword to filter cards",
      tryKeywords: "Try: Street Light, Solar, Facade, Stadium, OEM",
      noResults: "No results found.",
      results: "results",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Phone",
      scanToAdd: "Scan to add ZOMEI Lighting",
      scanToAddDescription: "Get product selection, quotation and project support.",
      whatsappQr: "WhatsApp QR",
      wechatQr: "WeChat QR",
      contactQrAlt: "Scan to add ZOMEI Lighting on WeChat",
      showCount: "Showing",
      projectCount: "projects",
      viewContent: "View Content",
      readFullArticle: "Read Full Article",
      continueReading: "Continue Reading",
    },
    homeCompany: {
      eyebrow: "ZOMEILED Factory",
      title: "Real Manufacturing Capability for Outdoor Lighting Project Delivery",
      description:
        "ZOMEILED focuses on LED outdoor landscape lighting and road lighting products, integrating R&D testing, manufacturing, quality control and project service to support stable supply for facades, landscapes, roads and commercial projects.",
      action: "Explore Company Capability",
      more: "More Company Capabilities",
      strengths: [
        ["R&D Testing", "Optical, electrical, waterproof and reliability validation"],
        ["Manufacturing", "SMT, potting, assembly and in-process inspection"],
        ["Project Support", "Selection, documents, quotation and installation coordination"],
      ],
      images: ["R&D Testing", "Manufacturing", "Company Environment"],
      imageAlts: ["ZOMEILED R&D testing equipment", "ZOMEILED production workshop", "ZOMEILED company exterior"],
    },
    blog: {
      title: "Lighting Knowledge & Project Insights",
      description:
        "Product guides, lighting design notes, project experience and outdoor lighting knowledge for buyers, designers and engineering teams.",
      categoryEyebrow: "Resource Categories",
      categoryDescription: "Browse product knowledge, lighting guides and project experience by topic.",
      allCategory: "All Resources",
      checklistTitle: "Project Selection Checklist",
      conclusionTitle: "Conclusion",
      relatedTitle: "Related Articles",
      breadcrumbCategory: "Lighting Resources",
      metaTitle: "Lighting Resources",
      metaDescription: "ZOMEI lighting knowledge, product guides, project insights and outdoor lighting industry resources.",
    },
    detail: {
      overview: "Overview",
      keyFeatures: "Key Features",
      applications: "Applications",
      specifications: "Specifications",
      projectScope: "Project Scope",
      projectHighlights: "Project Highlights",
      suitableFor: "Suitable For",
      designFocus: "Design Focus",
      recommendedProducts: "Recommended Product Mix",
      deliverables: "Solution Deliverables",
      engineeringNotes: "Engineering Notes",
      productType: "Product Type",
    },
    inquiry: {
      name: "Name",
      email: "Email",
      company: "Company",
      country: "Country",
      product: "Product Interested",
      details: "Project Details",
      submit: "Send Inquiry",
      sending: "Sending...",
      success: "Thank you! We will contact you soon.",
      error: "Error submitting your inquiry. Please try again.",
      selectProduct: "Select a product",
    },
    hero: {
      eyebrow: "Architectural · Landscape · Street · Solar",
      title: "Professional Outdoor Lighting Solutions",
      description:
        "Controlled light distribution for architectural facades, landscapes, roads and commercial outdoor projects.",
      primaryCta: "Explore Products",
      secondaryCta: "View Projects",
      sideEyebrow: "Built for international projects",
      sideTitle: "Precise Beam Control. Reliable Project Supply.",
      sideRoad: "Road & Street Lighting",
      sideLandscape: "Landscape & Garden Lighting",
      sideFacade: "Facade & Industrial Lighting",
      requestSolution: "Request a tailored solution",
    },
    sections: {
      productsEyebrow: "Product Categories",
      productsTitle: "Explore Our Outdoor Lighting Products",
      productsDescription:
        "High-quality outdoor lighting products with reliable performance, precise optics and clean project-ready structures.",
      featuredProductsTitle: "Featured Product Series",
      solutionsEyebrow: "Solutions",
      solutionsTitle: "Lighting Solutions for Every Outdoor Space",
      solutionsDescription:
        "Professional lighting design for facade, landscape, street, commercial and industrial applications.",
      projectsEyebrow: "Projects",
      projectsTitle: "Real Outdoor Lighting Project Cases",
      projectsDescription:
        "Selected project stories that show lighting design, product matching and on-site delivery.",
      whyEyebrow: "Why Choose Us",
      whyTitle: "Built on Quality, Driven by Innovation",
      whyDescription:
        "A premium outdoor lighting partner with stable manufacturing, professional support, and global project experience.",
      inquiryEyebrow: "Contact / Inquiry",
      inquiryTitle: "Have an Outdoor Lighting Project in Mind?",
      inquiryDescription: "Contact our lighting experts and get a professional solution within 24 hours.",
    },
    footer: {
      products: "Products",
      solutions: "Solutions",
      support: "Lighting Resources",
      company: "Company",
      streetLight: "Street Light",
      solarStreetLight: "Solar Street Light",
      floodLight: "Flood Light",
      solarFloodLight: "Solar Flood Light",
      gardenLight: "Garden Light",
      highBayLight: "High Bay Light",
      wallWasherLight: "Wall Washer Light",
      roadLighting: "Road Lighting",
      solarLighting: "Solar Lighting",
      landscapeLighting: "Landscape Lighting",
      buildingFacadeLighting: "Building Facade Lighting",
      industrialLighting: "Industrial Lighting",
      catalogDownload: "Catalog Download",
      installationGuide: "Lighting Guides",
      faq: "Product Knowledge",
      warranty: "Project Insights",
      contactSupport: "Industry Articles",
      aboutUs: "About Us",
      factory: "Factory",
      certifications: "Certifications",
      projects: "Projects",
      news: "News",
      description:
        "Premium outdoor lighting for engineering projects, distributors and international buyers.",
      copyright: "© 2026 ZOMEI. All rights reserved.",
      prototype: "Outdoor lighting brand website homepage prototype.",
    },
    pageHeader: {
      aboutEyebrow: "About Us",
      aboutTitle: "Professional Architectural Lighting Solutions",
      aboutDescription:
        "ZOMEI Lighting provides architectural lighting products, design consultation, technical support and international project delivery through an integrated manufacturing network.",
      aboutAction: "Talk to Us",
      projectsEyebrow: "Projects",
      projectsTitle: "Selected Real Project Cases",
      projectsDescription:
        "A focused project library for verified cases, with more references added as new work is completed.",
      projectsAction: "Share Project",
      solutionsEyebrow: "Solutions",
      solutionsTitle: "Lighting Solutions for Outdoor Projects",
      solutionsDescription:
        "Use solution pages to communicate engineering context, use cases, and the value of each lighting system.",
      solutionsAction: "Discuss Solution",
      contactEyebrow: "Contact",
      contactTitle: "Inquiry and Contact",
      contactDescription: "Use this page for direct contact details, inquiry form integration, and future quote requests.",
      contactAction: "Jump to Inquiry",
    },
    site: {
      brandTagline: "Outdoor lighting for global projects",
      stats: {
        yearsExperience: "Years Experience",
        projectsServed: "Projects Served",
        customization: "Customization",
        certifiedSupply: "Certified Supply",
        warranty: "Warranty",
      },
      why: {
        experience: {
          title: "15+ Years Outdoor Lighting Experience",
          description: "Stable process control and project delivery know-how.",
        },
        oem: {
          title: "OEM & ODM Support",
          description: "Flexible branding, structure and specification customization.",
        },
        team: {
          title: "Professional Engineering Team",
          description: "Fast response to technical issues and project requirements.",
        },
        quality: {
          title: "Strict Quality Control",
          description: "Stable manufacturing standards for long-term performance.",
        },
        cert: {
          title: "CE / RoHS / ISO Certifications",
          description: "Compliance-ready documentation for global markets.",
        },
        delivery: {
          title: "Fast Delivery",
          description: "Efficient production and dispatch for project timelines.",
        },
        global: {
          title: "Global Project Support",
          description: "Service workflow for distributors, contractors and buyers.",
        },
        warranty: {
          title: "5 Years Warranty",
          description: "Confidence in long-term reliability and maintenance.",
        },
      },
    },
  },
  zh: {
    menu: {
      products: "产品",
      solutions: "解决方案",
      projects: "项目",
      support: "照明知识",
      about: "关于我们",
      contact: "联系我们",
    },
    products: {
      wallWasher: "洗墙灯",
      linearLight: "线条灯",
      projectorLight: "投光灯",
      pointLight: "点光源",
      corrugatedLight: "瓦楞灯",
      columnLamp: "柱灯",
      windowSillLight: "窗台灯",
      stepLamp: "台阶灯",
      wallLamp: "壁灯",
      floodLight: "泛光灯",
      streetLight: "路灯",
      solarLight: "太阳能灯",
    },
    solutions: {
      roadStreet: "道路与街道照明",
      solar: "太阳能照明方案",
      landscape: "景观照明",
      facade: "建筑立面照明",
      industrial: "工业照明",
      gardenPark: "花园与公园照明",
      stadiumArea: "体育场与广场照明",
      urbanPublic: "城市公共照明",
    },
    projects: {
      almatyMuseum: "阿拉木图艺术博物馆外立面灯光",
      guangzhouDigitalCultureValley: "广东数字文化谷泛光照明更新改造项目",
      road: "道路照明项目",
      plaza: "商业广场照明",
      landscape: "景观公园照明",
      facade: "建筑立面照明",
    },
    common: {
      home: "首页",
      productCenter: "产品中心",
      quickInquiry: "快速询盘",
      search: "搜索",
      language: "语言",
      exploreProducts: "浏览产品",
      viewProjects: "查看项目",
      sendInquiry: "发送询盘",
      viewProducts: "查看产品",
      viewCase: "查看项目",
      exploreSolution: "查看方案",
      location: "地点",
      usedProducts: "使用产品",
      backToProducts: "返回产品",
      backToSolutions: "返回方案",
      backToProjects: "返回项目",
      learnMore: "了解更多",
      searchResults: "搜索产品、方案和项目",
      searchPlaceholder: "输入关键词筛选卡片",
      tryKeywords: "可试试：路灯、太阳能、立面、体育场、OEM",
      noResults: "未找到结果。",
      results: "条结果",
      whatsapp: "WhatsApp",
      email: "邮箱",
      phone: "电话",
      scanToAdd: "扫码添加 ZOMEI Lighting",
      scanToAddDescription: "获取产品选型、报价与项目支持。",
      whatsappQr: "WhatsApp 二维码",
      wechatQr: "微信二维码",
      contactQrAlt: "扫码添加 ZOMEI Lighting 微信",
      showCount: "当前显示",
      projectCount: "个项目",
      viewContent: "查看内容",
      readFullArticle: "阅读全文",
      continueReading: "继续阅读",
    },
    homeCompany: {
      eyebrow: "ZOMEILED Factory",
      title: "用真实制造能力支持户外照明项目交付",
      description:
        "ZOMEILED 专注 LED 户外景观照明和道路照明产品，围绕研发测试、生产制造、品质控制和项目服务，为建筑立面、景观空间、道路和商业工程提供稳定供应支持。",
      action: "了解公司实力",
      more: "查看更多公司能力",
      strengths: [
        ["研发测试", "光学、电气、防水与可靠性验证"],
        ["生产制造", "贴片、灌胶、装配与过程检验"],
        ["项目支持", "选型、资料、报价与安装沟通"],
      ],
      images: ["研发测试", "生产制造", "公司环境"],
      imageAlts: ["ZOMEILED 研发测试设备", "ZOMEILED 生产车间", "ZOMEILED 公司外部环境"],
    },
    blog: {
      title: "照明知识与项目洞察",
      description: "发布 ZOMEI 产品指南、照明设计笔记、项目经验和户外照明知识，服务采购方、设计师与工程团队。",
      categoryEyebrow: "资源分类",
      categoryDescription: "按主题快速浏览产品知识、照明指南与项目经验。",
      allCategory: "全部资源",
      checklistTitle: "项目选型检查清单",
      conclusionTitle: "结语",
      relatedTitle: "相关文章",
      breadcrumbCategory: "照明知识",
      metaTitle: "照明知识",
      metaDescription: "ZOMEI 照明知识、产品指南、项目洞察和户外照明行业资料。",
    },
    detail: {
      overview: "概述",
      keyFeatures: "核心特点",
      applications: "应用场景",
      specifications: "规格参数",
      projectScope: "项目范围",
      projectHighlights: "项目亮点",
      suitableFor: "适用场景",
      designFocus: "设计重点",
      recommendedProducts: "推荐产品组合",
      deliverables: "方案交付支持",
      engineeringNotes: "工程说明",
      productType: "产品类型",
    },
    inquiry: {
      name: "姓名",
      email: "邮箱",
      company: "公司",
      country: "国家",
      product: "感兴趣的产品",
      details: "项目描述",
      submit: "发送询盘",
      sending: "发送中...",
      success: "感谢您的联系，我们会尽快回复。",
      error: "提交失败，请稍后重试。",
      selectProduct: "请选择产品",
    },
    hero: {
      eyebrow: "建筑 · 景观 · 道路 · 太阳能",
      title: "专业户外照明解决方案",
      description: "以可控配光服务建筑立面、景观、道路和商业户外项目。",
      primaryCta: "浏览产品",
      secondaryCta: "查看项目",
      sideEyebrow: "适用于国际项目",
      sideTitle: "精准控光 · 稳定项目供货",
      sideRoad: "道路与街道照明",
      sideLandscape: "景观与花园照明",
      sideFacade: "立面与工业照明",
      requestSolution: "获取定制方案",
    },
    sections: {
      productsEyebrow: "产品分类",
      productsTitle: "探索我们的户外照明产品",
      productsDescription: "高品质户外照明产品，兼顾可靠性能、精准光学和清晰的工程安装结构。",
      featuredProductsTitle: "精选产品系列",
      solutionsEyebrow: "解决方案",
      solutionsTitle: "适用于各类户外空间的照明方案",
      solutionsDescription: "面向立面、景观、道路、商业和工业应用的专业照明设计方案。",
      projectsEyebrow: "项目",
      projectsTitle: "真实户外照明项目案例",
      projectsDescription: "通过已落地项目展示照明设计、产品匹配和现场交付能力。",
      whyEyebrow: "为什么选择我们",
      whyTitle: "以品质为基础，以创新驱动",
      whyDescription: "拥有稳定制造、专业支持以及全球项目经验的高品质户外照明合作伙伴。",
      inquiryEyebrow: "联系 / 询盘",
      inquiryTitle: "有户外照明项目想法？",
      inquiryDescription: "联系我们的照明专家，24 小时内获取专业方案。",
    },
    footer: {
      products: "产品",
      solutions: "解决方案",
      support: "照明知识",
      company: "公司",
      streetLight: "路灯",
      solarStreetLight: "太阳能路灯",
      floodLight: "泛光灯",
      solarFloodLight: "太阳能泛光灯",
      gardenLight: "花园灯",
      highBayLight: "高棚灯",
      wallWasherLight: "洗墙灯",
      roadLighting: "道路照明",
      solarLighting: "太阳能照明",
      landscapeLighting: "景观照明",
      buildingFacadeLighting: "建筑立面照明",
      industrialLighting: "工业照明",
      catalogDownload: "目录下载",
      installationGuide: "照明指南",
      faq: "产品知识",
      warranty: "项目洞察",
      contactSupport: "行业文章",
      aboutUs: "关于我们",
      factory: "工厂",
      certifications: "认证",
      projects: "项目",
      news: "新闻",
      description: "面向工程项目、经销商和国际采购方的高品质户外照明。",
      copyright: "© 2026 ZOMEI. 保留所有权利。",
      prototype: "户外照明品牌网站首页原型。",
    },
    pageHeader: {
      aboutEyebrow: "关于我们",
      aboutTitle: "专业建筑照明解决方案",
      aboutDescription: "深圳卓美LED（ZOMEI Lighting）依托多制造基地协同体系，为建筑照明、景观照明、文旅夜游及智能控制项目提供产品供应、设计咨询、技术支持和国际项目交付服务。",
      aboutAction: "联系我们",
      projectsEyebrow: "项目",
      projectsTitle: "精选真实项目案例",
      projectsDescription: "当前仅展示已整理的真实项目，后续案例可持续补充。",
      projectsAction: "提交项目",
      solutionsEyebrow: "解决方案",
      solutionsTitle: "适用于户外项目的照明方案",
      solutionsDescription: "用方案页清晰传达工程语境、使用场景和每套照明系统的价值。",
      solutionsAction: "讨论方案",
      contactEyebrow: "联系",
      contactTitle: "联系与询盘",
      contactDescription: "用于直达联系方式、询盘表单集成，以及后续报价需求。",
      contactAction: "跳转询盘",
    },
    site: {
      brandTagline: "面向全球项目的户外照明",
      stats: {
        yearsExperience: "年经验",
        projectsServed: "项目服务",
        customization: "定制能力",
        certifiedSupply: "认证供货",
        warranty: "质保",
      },
      why: {
        experience: {
          title: "15年以上户外照明经验",
          description: "稳定的流程控制和项目交付经验。",
        },
        oem: {
          title: "OEM / ODM 支持",
          description: "灵活的品牌、结构与规格定制。",
        },
        team: {
          title: "专业工程团队",
          description: "快速响应技术问题和项目需求。",
        },
        quality: {
          title: "严格质量控制",
          description: "面向长期性能的稳定制造标准。",
        },
        cert: {
          title: "CE / RoHS / ISO 认证",
          description: "适用于全球市场的合规资料支持。",
        },
        delivery: {
          title: "快速交付",
          description: "适配项目周期的高效生产与发货。",
        },
        global: {
          title: "全球项目支持",
          description: "适用于经销商、承包商和采购方的服务流程。",
        },
        warranty: {
          title: "5年质保",
          description: "让长期可靠性与维护更有保障。",
        },
      },
    },
  },
  ru: {
    menu: {
      products: "Продукция",
      solutions: "Решения",
      projects: "Проекты",
      support: "Lighting Resources",
      about: "О компании",
      contact: "Контакты",
    },
    products: {
      wallWasher: "Светильник для подсветки стен",
      linearLight: "Линейный светильник",
      projectorLight: "Проекторный светильник",
      pointLight: "Точечный светильник",
      corrugatedLight: "Кровельный светильник",
      columnLamp: "Колонный светильник",
      windowSillLight: "Светильник для подоконников",
      stepLamp: "Ступенчатый светильник",
      wallLamp: "Настенный светильник",
      floodLight: "Прожектор",
      streetLight: "Уличный светильник",
      solarLight: "Солнечный светильник",
    },
    solutions: {
      roadStreet: "Освещение дорог и улиц",
      solar: "Солнечное освещение",
      landscape: "Ландшафтное освещение",
      facade: "Подсветка фасадов",
      industrial: "Промышленное освещение",
      gardenPark: "Освещение садов и парков",
      stadiumArea: "Освещение стадионов и площадей",
      urbanPublic: "Городское общественное освещение",
    },
    projects: {
      almatyMuseum: "Фасадное освещение Almaty Museum of Arts",
      guangzhouDigitalCultureValley: "Фасадное освещение Guangzhou Digital Culture Valley",
      road: "Проект дорожного освещения",
      plaza: "Освещение коммерческой площади",
      landscape: "Освещение парка",
      facade: "Освещение фасада здания",
    },
    common: {
      home: "Главная",
      productCenter: "Центр продукции",
      quickInquiry: "Быстрый запрос",
      search: "Поиск",
      language: "Язык",
      exploreProducts: "Смотреть продукцию",
      viewProjects: "Смотреть проекты",
      sendInquiry: "Отправить запрос",
      viewProducts: "Смотреть продукцию",
      viewCase: "Смотреть проект",
      exploreSolution: "Смотреть решение",
      location: "Локация",
      usedProducts: "Используемая продукция",
      backToProducts: "Назад к продукции",
      backToSolutions: "Назад к решениям",
      backToProjects: "Назад к проектам",
      learnMore: "Узнать больше",
      searchResults: "Искать продукты, решения и проекты",
      searchPlaceholder: "Введите ключевое слово для фильтрации",
      tryKeywords: "Попробуйте: Street Light, Solar, Facade, Stadium, OEM",
      noResults: "Результаты не найдены.",
      results: "результатов",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Телефон",
      scanToAdd: "Сканируйте, чтобы добавить ZOMEI Lighting",
      scanToAddDescription: "Получите подбор продукции, расчет и поддержку проекта.",
      whatsappQr: "WhatsApp QR",
      wechatQr: "WeChat QR",
      contactQrAlt: "Сканируйте, чтобы добавить ZOMEI Lighting в WeChat",
      showCount: "Показано",
      projectCount: "проектов",
      viewContent: "Открыть материал",
      readFullArticle: "Читать полностью",
      continueReading: "Продолжить чтение",
    },
    homeCompany: {
      eyebrow: "ZOMEILED Factory",
      title: "Реальные производственные возможности для поставки проектов наружного освещения",
      description:
        "ZOMEILED специализируется на LED-решениях для наружного ландшафтного и дорожного освещения, объединяя R&D-тестирование, производство, контроль качества и проектный сервис для фасадов, ландшафтов, дорог и коммерческих объектов.",
      action: "Изучить возможности компании",
      more: "Больше о возможностях компании",
      strengths: [
        ["R&D-тестирование", "Оптическая, электрическая, влагозащитная и ресурсная проверка"],
        ["Производство", "SMT-монтаж, заливка, сборка и межоперационный контроль"],
        ["Проектная поддержка", "Подбор, документация, расчет и координация монтажа"],
      ],
      images: ["R&D-тестирование", "Производство", "Среда компании"],
      imageAlts: ["Испытательное оборудование ZOMEILED", "Производственный цех ZOMEILED", "Внешний вид компании ZOMEILED"],
    },
    blog: {
      title: "Знания об освещении и проектные материалы",
      description:
        "Руководства по продукции, заметки по светодизайну, проектный опыт и знания о наружном освещении для закупщиков, дизайнеров и инженерных команд.",
      categoryEyebrow: "Категории материалов",
      categoryDescription: "Быстрый просмотр знаний о продукции, руководств по свету и проектного опыта.",
      allCategory: "Все материалы",
      checklistTitle: "Чек-лист подбора для проекта",
      conclusionTitle: "Заключение",
      relatedTitle: "Похожие статьи",
      breadcrumbCategory: "Lighting Resources",
      metaTitle: "Lighting Resources",
      metaDescription: "Знания ZOMEI об освещении, руководства по продукции, проектные материалы и отраслевые ресурсы.",
    },
    detail: {
      overview: "Обзор",
      keyFeatures: "Ключевые особенности",
      applications: "Применение",
      specifications: "Спецификации",
      projectScope: "Область проекта",
      projectHighlights: "Особенности проекта",
      suitableFor: "Подходит для",
      designFocus: "Фокус проектирования",
      recommendedProducts: "Рекомендуемая продуктовая комбинация",
      deliverables: "Материалы по решению",
      engineeringNotes: "Инженерные примечания",
      productType: "Тип продукта",
    },
    inquiry: {
      name: "Имя",
      email: "Email",
      company: "Компания",
      country: "Страна",
      product: "Интересующий продукт",
      details: "Описание проекта",
      submit: "Отправить запрос",
      sending: "Отправка...",
      success: "Спасибо! Мы свяжемся с вами скоро.",
      error: "Не удалось отправить запрос. Попробуйте еще раз.",
      selectProduct: "Выберите продукт",
    },
    hero: {
      eyebrow: "Бренд уличного освещения · Инженерный класс",
      title: "Профессиональное уличное освещение для глобальных проектов",
      description:
        "Высокопроизводительные LED-решения для дорог, ландшафтов, зданий и промышленных объектов.",
      primaryCta: "Смотреть продукцию",
      secondaryCta: "Смотреть проекты",
      sideEyebrow: "Для международных проектов",
      sideTitle: "Стабильные поставки · Понятные спецификации · Быстрый ответ",
      sideRoad: "Освещение дорог и улиц",
      sideLandscape: "Ландшафтное и садовое освещение",
      sideFacade: "Фасадное и промышленное освещение",
      requestSolution: "Запросить индивидуальное решение",
    },
    sections: {
      productsEyebrow: "Категории продукции",
      productsTitle: "Изучите нашу продукцию для наружного освещения",
      productsDescription: "Удобная структура для быстрого просмотра, чтения спецификаций и дальнейшего расширения.",
      featuredProductsTitle: "Избранные серии продукции",
      solutionsEyebrow: "Решения",
      solutionsTitle: "Решения для любого наружного пространства",
      solutionsDescription:
        "Визуальная карта решений для дорог, ландшафта, фасадов, промышленных зон и городской среды.",
      projectsEyebrow: "Проекты",
      projectsTitle: "Реальные проекты наружного освещения",
      projectsDescription: "Избранные кейсы, показывающие дизайн, подбор продукции и работу на объекте.",
      whyEyebrow: "Почему мы",
      whyTitle: "Для инженерных проектов, а не для шаблонных лендингов",
      whyDescription: "Партнёр с надёжным производством, профессиональной поддержкой и мировым опытом проектов.",
      inquiryEyebrow: "Контакт / Запрос",
      inquiryTitle: "Есть проект по наружному освещению?",
      inquiryDescription: "Свяжитесь с нашими экспертами и получите решение в течение 24 часов.",
    },
    footer: {
      products: "Продукция",
      solutions: "Решения",
      support: "Lighting Resources",
      company: "Компания",
      streetLight: "Уличный светильник",
      solarStreetLight: "Солнечный уличный светильник",
      floodLight: "Прожектор",
      solarFloodLight: "Солнечный прожектор",
      gardenLight: "Садовый светильник",
      highBayLight: "Промышленный светильник",
      wallWasherLight: "Светильник для подсветки стен",
      roadLighting: "Освещение дорог",
      solarLighting: "Солнечное освещение",
      landscapeLighting: "Ландшафтное освещение",
      buildingFacadeLighting: "Подсветка фасадов",
      industrialLighting: "Промышленное освещение",
      catalogDownload: "Скачать каталог",
      installationGuide: "Руководства по свету",
      faq: "Знания о продукции",
      warranty: "Проектные статьи",
      contactSupport: "Отраслевые материалы",
      aboutUs: "О компании",
      factory: "Фабрика",
      certifications: "Сертификаты",
      projects: "Проекты",
      news: "Новости",
      description: "Премиальное наружное освещение для инженерных проектов и международных покупателей.",
      copyright: "© 2026 ZOMEI. Все права защищены.",
      prototype: "Прототип главной страницы сайта бренда наружного освещения.",
    },
    pageHeader: {
      aboutEyebrow: "О компании",
      aboutTitle: "Бренд освещения для проектных процессов",
      aboutDescription: "Позже эту страницу можно расширить блоками о фабрике, сертификации и команде.",
      aboutAction: "Связаться с нами",
      projectsEyebrow: "Проекты",
      projectsTitle: "Избранные реальные кейсы",
      projectsDescription: "Здесь показаны только подготовленные реальные проекты; новые кейсы можно добавлять постепенно.",
      projectsAction: "Поделиться проектом",
      solutionsEyebrow: "Решения",
      solutionsTitle: "Решения наружного освещения",
      solutionsDescription: "Страницы решений должны передавать инженерный контекст и ценность системы освещения.",
      solutionsAction: "Обсудить решение",
      contactEyebrow: "Контакты",
      contactTitle: "Запрос и контакты",
      contactDescription: "Здесь можно разместить прямые контакты, форму запроса и будущие коммерческие заявки.",
      contactAction: "К форме",
    },
    site: {
      brandTagline: "Уличное освещение для глобальных проектов",
      stats: {
        yearsExperience: "Лет опыта",
        projectsServed: "Проектов",
        customization: "Кастомизация",
        certifiedSupply: "Сертифицированные поставки",
        warranty: "Гарантия",
      },
      why: {
        experience: {
          title: "15+ лет опыта в наружном освещении",
          description: "Стабильный процесс и опыт поставок для проектов.",
        },
        oem: {
          title: "Поддержка OEM & ODM",
          description: "Гибкая кастомизация бренда, конструкции и спецификаций.",
        },
        team: {
          title: "Профессиональная инженерная команда",
          description: "Быстрый ответ на технические вопросы и требования.",
        },
        quality: {
          title: "Строгий контроль качества",
          description: "Стабильные стандарты производства для долгой службы.",
        },
        cert: {
          title: "Сертификаты CE / RoHS / ISO",
          description: "Документы для соответствия требованиям мировых рынков.",
        },
        delivery: {
          title: "Быстрая поставка",
          description: "Эффективное производство и отправка под сроки проекта.",
        },
        global: {
          title: "Поддержка глобальных проектов",
          description: "Процесс работы для дистрибьюторов, подрядчиков и закупщиков.",
        },
        warranty: {
          title: "Гарантия 5 лет",
          description: "Уверенность в надёжности и обслуживании.",
        },
      },
    },
  },
};

type LanguageContextType = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => any;
};

const STORAGE_KEY = "zhuomei_locale";

const LanguageContext = createContext<LanguageContextType>({
  locale: "zh",
  setLocale: () => {},
  t: (key: string) => key,
});

function getByPath(source: any, path: string) {
  return path.split(".").reduce((value, part) => (value ? value[part] : undefined), source);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("zh");

  useEffect(() => {
    const storedLocale =
      typeof window !== "undefined"
        ? (window.localStorage.getItem(STORAGE_KEY) as Locale | null)
        : null;
    const nextLocale = storedLocale && dictionaries[storedLocale] ? storedLocale : "zh";

    setLocaleState(nextLocale);
    document.documentElement.lang = nextLocale;
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, nextLocale);
    }
  }, []);

  const setLocale = (nextLocale: Locale) => {
    setLocaleState(nextLocale);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, nextLocale);
    }
    document.documentElement.lang = nextLocale;
  };

  const t = useMemo(() => {
    return (key: string) => getByPath(dictionaries[locale], key) ?? key;
  }, [locale]);

  return <LanguageContext.Provider value={{ locale, setLocale, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
