"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type Dictionaries = Record<string, Record<string, any>>;

const dictionaries: Dictionaries = {
  en: {
    menu: {
      products: "Products",
      solutions: "Solutions",
      projects: "Projects",
      support: "Support",
      about: "About Us",
      contact: "Contact",
    },
    products: {
      streetLight: "Street Light",
      solarStreetLight: "Solar Street Light",
      floodLight: "Flood Light",
      solarFloodLight: "Solar Flood Light",
      solarGardenLight: "Solar Garden Light",
      highBayLight: "High Bay Light",
      moistureProof: "Moisture Proof Lamps",
      wallWasher: "Wall Washer Light",
      linearLight: "Linear Light",
      projectorLight: "Projector Light",
      pointLight: "Point Light Source",
    },
    solutions: {
      roadStreet: "Road & Street Lighting",
      solar: "Solar Lighting Solution",
      landscape: "Landscape Lighting",
      facade: "Building Facade Lighting",
      industrial: "Industrial Lighting",
      gardenPark: "Garden & Park Lighting",
      stadiumArea: "Stadium & Area Lighting",
      urbanPublic: "Urban Public Lighting",
    },
    projects: {
      road: "Road Lighting Project",
      plaza: "Commercial Plaza Lighting",
      landscape: "Landscape Park Lighting",
      facade: "Building Facade Lighting",
    },
    common: {
      quickInquiry: "Quick Inquiry",
      search: "Search",
      language: "Language",
      exploreProducts: "Explore Products",
      viewProjects: "View Projects",
      sendInquiry: "Send Inquiry",
      viewProducts: "View Products",
      viewCase: "View Case",
      exploreSolution: "Explore Solution",
      location: "Location",
      usedProducts: "Used Products",
      backToProducts: "Back to Products",
      backToSolutions: "Back to Solutions",
      backToProjects: "Back to Projects",
      learnMore: "Learn More",
      searchResults: "Search products, solutions and projects",
      searchPlaceholder: "Type a keyword to filter cards",
      tryKeywords: "Try: Street Light, Solar, Facade, Stadium, OEM",
      noResults: "No results found.",
      results: "results",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Phone",
    },
    inquiry: {
      name: "Name",
      email: "Email",
      company: "Company",
      country: "Country",
      product: "Product Interested",
      details: "Project Details",
      submit: "Send Inquiry",
      sending: "Sending...",
      success: "Thank you! We will contact you soon.",
      error: "Error submitting your inquiry. Please try again.",
      selectProduct: "Select a product",
    },
    hero: {
      eyebrow: "Outdoor Lighting Brand · Engineering Grade",
      title: "Professional Outdoor Lighting for Global Projects",
      description:
        "High-performance LED lighting solutions for roads, landscapes, buildings and industrial spaces.",
      primaryCta: "Explore Products",
      secondaryCta: "View Projects",
      sideEyebrow: "Built for international projects",
      sideTitle: "Reliable Supply. Clear Specs. Fast Response.",
      sideRoad: "Road & Street Lighting",
      sideLandscape: "Landscape & Garden Lighting",
      sideFacade: "Facade & Industrial Lighting",
      requestSolution: "Request a tailored solution",
    },
    sections: {
      productsEyebrow: "Product Categories",
      productsTitle: "Explore Our Outdoor Lighting Products",
      productsDescription:
        "Structured product categories designed for fast browsing, clear specification reading, and future product-detail expansion.",
      solutionsEyebrow: "Solutions",
      solutionsTitle: "Lighting Solutions for Every Outdoor Space",
      solutionsDescription:
        "A visual solution map for road infrastructure, landscape, building facades, industrial sites and urban public environments.",
      projectsEyebrow: "Projects",
      projectsTitle: "Inspiring Outdoor Lighting Projects Worldwide",
      projectsDescription:
        "Use this section to show project credibility, application context, and the visual value of the brand.",
      whyEyebrow: "Why Choose Us",
      whyTitle: "Built for Engineering Projects, Not Template Sales Pages",
      whyDescription:
        "A premium outdoor lighting partner with stable manufacturing, professional support, and global project experience.",
      inquiryEyebrow: "Contact / Inquiry",
      inquiryTitle: "Have an Outdoor Lighting Project in Mind?",
      inquiryDescription: "Contact our lighting experts and get a professional solution within 24 hours.",
    },
    footer: {
      products: "Products",
      solutions: "Solutions",
      support: "Support",
      company: "Company",
      streetLight: "Street Light",
      solarStreetLight: "Solar Street Light",
      floodLight: "Flood Light",
      solarFloodLight: "Solar Flood Light",
      gardenLight: "Garden Light",
      highBayLight: "High Bay Light",
      wallWasherLight: "Wall Washer Light",
      roadLighting: "Road Lighting",
      solarLighting: "Solar Lighting",
      landscapeLighting: "Landscape Lighting",
      buildingFacadeLighting: "Building Facade Lighting",
      industrialLighting: "Industrial Lighting",
      catalogDownload: "Catalog Download",
      installationGuide: "Installation Guide",
      faq: "FAQ",
      warranty: "Warranty",
      contactSupport: "Contact Support",
      aboutUs: "About Us",
      factory: "Factory",
      certifications: "Certifications",
      projects: "Projects",
      news: "News",
      description:
        "Premium outdoor lighting for engineering projects, distributors and international buyers.",
      copyright: "© 2026 ZHUOMEI LIGHTING. All rights reserved.",
      prototype: "Outdoor lighting brand website homepage prototype.",
    },
    pageHeader: {
      aboutEyebrow: "About Us",
      aboutTitle: "A Lighting Brand Built for Project Workflows",
      aboutDescription:
        "This page can later expand into factory, certifications, team and manufacturing capability sections.",
      aboutAction: "Talk to Us",
      projectsEyebrow: "Projects",
      projectsTitle: "Inspiring Outdoor Lighting Projects",
      projectsDescription:
        "Project pages should make credibility clear fast: location, application, and product fit.",
      projectsAction: "Share Project",
      solutionsEyebrow: "Solutions",
      solutionsTitle: "Lighting Solutions for Outdoor Projects",
      solutionsDescription:
        "Use solution pages to communicate engineering context, use cases, and the value of each lighting system.",
      solutionsAction: "Discuss Solution",
      contactEyebrow: "Contact",
      contactTitle: "Inquiry and Contact",
      contactDescription: "Use this page for direct contact details, inquiry form integration, and future quote requests.",
      contactAction: "Jump to Inquiry",
    },
    site: {
      brandTagline: "Outdoor lighting for global projects",
      stats: {
        yearsExperience: "Years Experience",
        projectsServed: "Projects Served",
        customization: "Customization",
        certifiedSupply: "Certified Supply",
        warranty: "Warranty",
      },
      why: {
        experience: {
          title: "15+ Years Outdoor Lighting Experience",
          description: "Stable process control and project delivery know-how.",
        },
        oem: {
          title: "OEM & ODM Support",
          description: "Flexible branding, structure and specification customization.",
        },
        team: {
          title: "Professional Engineering Team",
          description: "Fast response to technical issues and project requirements.",
        },
        quality: {
          title: "Strict Quality Control",
          description: "Stable manufacturing standards for long-term performance.",
        },
        cert: {
          title: "CE / RoHS / ISO Certifications",
          description: "Compliance-ready documentation for global markets.",
        },
        delivery: {
          title: "Fast Delivery",
          description: "Efficient production and dispatch for project timelines.",
        },
        global: {
          title: "Global Project Support",
          description: "Service workflow for distributors, contractors and buyers.",
        },
        warranty: {
          title: "5 Years Warranty",
          description: "Confidence in long-term reliability and maintenance.",
        },
      },
    },
  },
  zh: {
    menu: {
      products: "产品",
      solutions: "解决方案",
      projects: "案例",
      support: "支持",
      about: "关于我们",
      contact: "联系我们",
    },
    products: {
      streetLight: "路灯",
      solarStreetLight: "太阳能路灯",
      floodLight: "泛光灯",
      solarFloodLight: "太阳能泛光灯",
      solarGardenLight: "太阳能花园灯",
      highBayLight: "高棚灯",
      moistureProof: "防潮灯",
      wallWasher: "洗墙灯",
      linearLight: "线条灯",
      projectorLight: "投光灯",
      pointLight: "点光源",
    },
    solutions: {
      roadStreet: "道路与街道照明",
      solar: "太阳能照明方案",
      landscape: "景观照明",
      facade: "建筑立面照明",
      industrial: "工业照明",
      gardenPark: "花园与公园照明",
      stadiumArea: "体育场与广场照明",
      urbanPublic: "城市公共照明",
    },
    projects: {
      road: "道路照明项目",
      plaza: "商业广场照明",
      landscape: "景观公园照明",
      facade: "建筑立面照明",
    },
    common: {
      quickInquiry: "快速询盘",
      search: "搜索",
      language: "语言",
      exploreProducts: "浏览产品",
      viewProjects: "查看案例",
      sendInquiry: "发送询盘",
      viewProducts: "查看产品",
      viewCase: "查看案例",
      exploreSolution: "查看方案",
      location: "地点",
      usedProducts: "使用产品",
      backToProducts: "返回产品",
      backToSolutions: "返回方案",
      backToProjects: "返回案例",
      learnMore: "了解更多",
      searchResults: "搜索产品、方案和案例",
      searchPlaceholder: "输入关键词筛选卡片",
      tryKeywords: "可试试：路灯、太阳能、立面、体育场、OEM",
      noResults: "未找到结果。",
      results: "条结果",
      whatsapp: "WhatsApp",
      email: "邮箱",
      phone: "电话",
    },
    inquiry: {
      name: "姓名",
      email: "邮箱",
      company: "公司",
      country: "国家",
      product: "感兴趣的产品",
      details: "项目描述",
      submit: "发送询盘",
      sending: "发送中...",
      success: "感谢您的联系，我们会尽快回复。",
      error: "提交失败，请稍后重试。",
      selectProduct: "请选择产品",
    },
    hero: {
      eyebrow: "户外照明品牌 · 工程级",
      title: "面向全球项目的专业户外照明",
      description: "用于道路、景观、建筑与工业空间的高性能 LED 照明解决方案。",
      primaryCta: "浏览产品",
      secondaryCta: "查看案例",
      sideEyebrow: "适用于国际项目",
      sideTitle: "稳定供货 · 清晰规格 · 快速响应",
      sideRoad: "道路与街道照明",
      sideLandscape: "景观与花园照明",
      sideFacade: "立面与工业照明",
      requestSolution: "获取定制方案",
    },
    sections: {
      productsEyebrow: "产品分类",
      productsTitle: "探索我们的户外照明产品",
      productsDescription: "便于快速浏览、清晰阅读规格，并为后续产品详情页扩展留好结构。",
      solutionsEyebrow: "解决方案",
      solutionsTitle: "适用于各类户外空间的照明方案",
      solutionsDescription: "面向道路基础设施、景观、建筑立面、工业场景和城市公共空间的视觉方案地图。",
      projectsEyebrow: "项目案例",
      projectsTitle: "全球户外照明项目案例",
      projectsDescription: "用项目案例快速展示可信度、应用场景和品牌价值。",
      whyEyebrow: "为什么选择我们",
      whyTitle: "面向工程项目，而不是模板化销售页面",
      whyDescription: "拥有稳定制造、专业支持以及全球项目经验的高品质户外照明合作伙伴。",
      inquiryEyebrow: "联系 / 询盘",
      inquiryTitle: "有户外照明项目想法？",
      inquiryDescription: "联系我们的照明专家，24 小时内获取专业方案。",
    },
    footer: {
      products: "产品",
      solutions: "解决方案",
      support: "支持",
      company: "公司",
      streetLight: "路灯",
      solarStreetLight: "太阳能路灯",
      floodLight: "泛光灯",
      solarFloodLight: "太阳能泛光灯",
      gardenLight: "花园灯",
      highBayLight: "高棚灯",
      wallWasherLight: "洗墙灯",
      roadLighting: "道路照明",
      solarLighting: "太阳能照明",
      landscapeLighting: "景观照明",
      buildingFacadeLighting: "建筑立面照明",
      industrialLighting: "工业照明",
      catalogDownload: "目录下载",
      installationGuide: "安装指南",
      faq: "常见问题",
      warranty: "质保",
      contactSupport: "联系支持",
      aboutUs: "关于我们",
      factory: "工厂",
      certifications: "认证",
      projects: "案例",
      news: "新闻",
      description: "面向工程项目、经销商和国际采购方的高品质户外照明。",
      copyright: "© 2026 ZHUOMEI LIGHTING. 保留所有权利。",
      prototype: "户外照明品牌网站首页原型。",
    },
    pageHeader: {
      aboutEyebrow: "关于我们",
      aboutTitle: "面向项目流程的照明品牌",
      aboutDescription: "此页面后续可扩展为工厂、认证、团队和制造能力等内容。",
      aboutAction: "联系我们",
      projectsEyebrow: "项目案例",
      projectsTitle: "全球户外照明项目案例",
      projectsDescription: "项目页应快速展示可信度、应用场景和产品匹配。",
      projectsAction: "提交项目",
      solutionsEyebrow: "解决方案",
      solutionsTitle: "适用于户外项目的照明方案",
      solutionsDescription: "用方案页清晰传达工程语境、使用场景和每套照明系统的价值。",
      solutionsAction: "讨论方案",
      contactEyebrow: "联系",
      contactTitle: "联系与询盘",
      contactDescription: "用于直达联系方式、询盘表单集成，以及后续报价需求。",
      contactAction: "跳转询盘",
    },
    site: {
      brandTagline: "面向全球项目的户外照明",
      stats: {
        yearsExperience: "年经验",
        projectsServed: "项目服务",
        customization: "定制能力",
        certifiedSupply: "认证供货",
        warranty: "质保",
      },
      why: {
        experience: {
          title: "15年以上户外照明经验",
          description: "稳定的流程控制和项目交付经验。",
        },
        oem: {
          title: "OEM / ODM 支持",
          description: "灵活的品牌、结构与规格定制。",
        },
        team: {
          title: "专业工程团队",
          description: "快速响应技术问题和项目需求。",
        },
        quality: {
          title: "严格质量控制",
          description: "面向长期性能的稳定制造标准。",
        },
        cert: {
          title: "CE / RoHS / ISO 认证",
          description: "适用于全球市场的合规资料支持。",
        },
        delivery: {
          title: "快速交付",
          description: "适配项目周期的高效生产与发货。",
        },
        global: {
          title: "全球项目支持",
          description: "适用于经销商、承包商和采购方的服务流程。",
        },
        warranty: {
          title: "5年质保",
          description: "让长期可靠性与维护更有保障。",
        },
      },
    },
  },
  ru: {
    menu: {
      products: "Продукция",
      solutions: "Решения",
      projects: "Проекты",
      support: "Поддержка",
      about: "О компании",
      contact: "Контакты",
    },
    products: {
      streetLight: "Уличный светильник",
      solarStreetLight: "Солнечный уличный светильник",
      floodLight: "Прожектор",
      solarFloodLight: "Солнечный прожектор",
      solarGardenLight: "Садовый светильник на солнечной энергии",
      highBayLight: "Промышленный светильник",
      moistureProof: "Влагозащитный светильник",
      wallWasher: "Светильник для подсветки стен",
      linearLight: "Линейный светильник",
      projectorLight: "Проекторный светильник",
      pointLight: "Точечный светильник",
    },
    solutions: {
      roadStreet: "Освещение дорог и улиц",
      solar: "Солнечное освещение",
      landscape: "Ландшафтное освещение",
      facade: "Подсветка фасадов",
      industrial: "Промышленное освещение",
      gardenPark: "Освещение садов и парков",
      stadiumArea: "Освещение стадионов и площадей",
      urbanPublic: "Городское общественное освещение",
    },
    projects: {
      road: "Проект дорожного освещения",
      plaza: "Освещение коммерческой площади",
      landscape: "Освещение парка",
      facade: "Освещение фасада здания",
    },
    common: {
      quickInquiry: "Быстрый запрос",
      search: "Поиск",
      language: "Язык",
      exploreProducts: "Смотреть продукцию",
      viewProjects: "Смотреть проекты",
      sendInquiry: "Отправить запрос",
      viewProducts: "Смотреть продукцию",
      viewCase: "Смотреть кейс",
      exploreSolution: "Смотреть решение",
      location: "Локация",
      usedProducts: "Используемая продукция",
      backToProducts: "Назад к продукции",
      backToSolutions: "Назад к решениям",
      backToProjects: "Назад к проектам",
      learnMore: "Узнать больше",
      searchResults: "Искать продукты, решения и проекты",
      searchPlaceholder: "Введите ключевое слово для фильтрации",
      tryKeywords: "Попробуйте: Street Light, Solar, Facade, Stadium, OEM",
      noResults: "Результаты не найдены.",
      results: "результатов",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Телефон",
    },
    inquiry: {
      name: "Имя",
      email: "Email",
      company: "Компания",
      country: "Страна",
      product: "Интересующий продукт",
      details: "Описание проекта",
      submit: "Отправить запрос",
      sending: "Отправка...",
      success: "Спасибо! Мы свяжемся с вами скоро.",
      error: "Не удалось отправить запрос. Попробуйте еще раз.",
      selectProduct: "Выберите продукт",
    },
    hero: {
      eyebrow: "Бренд уличного освещения · Инженерный класс",
      title: "Профессиональное уличное освещение для глобальных проектов",
      description:
        "Высокопроизводительные LED-решения для дорог, ландшафтов, зданий и промышленных объектов.",
      primaryCta: "Смотреть продукцию",
      secondaryCta: "Смотреть проекты",
      sideEyebrow: "Для международных проектов",
      sideTitle: "Стабильные поставки · Понятные спецификации · Быстрый ответ",
      sideRoad: "Освещение дорог и улиц",
      sideLandscape: "Ландшафтное и садовое освещение",
      sideFacade: "Фасадное и промышленное освещение",
      requestSolution: "Запросить индивидуальное решение",
    },
    sections: {
      productsEyebrow: "Категории продукции",
      productsTitle: "Изучите нашу продукцию для наружного освещения",
      productsDescription: "Удобная структура для быстрого просмотра, чтения спецификаций и дальнейшего расширения.",
      solutionsEyebrow: "Решения",
      solutionsTitle: "Решения для любого наружного пространства",
      solutionsDescription:
        "Визуальная карта решений для дорог, ландшафта, фасадов, промышленных зон и городской среды.",
      projectsEyebrow: "Проекты",
      projectsTitle: "Вдохновляющие проекты наружного освещения по всему миру",
      projectsDescription: "Покажите доверие к бренду, контекст применения и визуальную ценность.",
      whyEyebrow: "Почему мы",
      whyTitle: "Для инженерных проектов, а не для шаблонных лендингов",
      whyDescription: "Партнёр с надёжным производством, профессиональной поддержкой и мировым опытом проектов.",
      inquiryEyebrow: "Контакт / Запрос",
      inquiryTitle: "Есть проект по наружному освещению?",
      inquiryDescription: "Свяжитесь с нашими экспертами и получите решение в течение 24 часов.",
    },
    footer: {
      products: "Продукция",
      solutions: "Решения",
      support: "Поддержка",
      company: "Компания",
      streetLight: "Уличный светильник",
      solarStreetLight: "Солнечный уличный светильник",
      floodLight: "Прожектор",
      solarFloodLight: "Солнечный прожектор",
      gardenLight: "Садовый светильник",
      highBayLight: "Промышленный светильник",
      wallWasherLight: "Светильник для подсветки стен",
      roadLighting: "Освещение дорог",
      solarLighting: "Солнечное освещение",
      landscapeLighting: "Ландшафтное освещение",
      buildingFacadeLighting: "Подсветка фасадов",
      industrialLighting: "Промышленное освещение",
      catalogDownload: "Скачать каталог",
      installationGuide: "Руководство по установке",
      faq: "FAQ",
      warranty: "Гарантия",
      contactSupport: "Связаться с поддержкой",
      aboutUs: "О компании",
      factory: "Фабрика",
      certifications: "Сертификаты",
      projects: "Проекты",
      news: "Новости",
      description: "Премиальное наружное освещение для инженерных проектов и международных покупателей.",
      copyright: "© 2026 ZHUOMEI LIGHTING. Все права защищены.",
      prototype: "Прототип главной страницы сайта бренда наружного освещения.",
    },
    pageHeader: {
      aboutEyebrow: "О компании",
      aboutTitle: "Бренд освещения для проектных процессов",
      aboutDescription: "Позже эту страницу можно расширить блоками о фабрике, сертификации и команде.",
      aboutAction: "Связаться с нами",
      projectsEyebrow: "Проекты",
      projectsTitle: "Вдохновляющие проекты наружного освещения",
      projectsDescription: "Страница проекта должна быстро показывать доверие, применение и соответствие продукта.",
      projectsAction: "Поделиться проектом",
      solutionsEyebrow: "Решения",
      solutionsTitle: "Решения наружного освещения",
      solutionsDescription: "Страницы решений должны передавать инженерный контекст и ценность системы освещения.",
      solutionsAction: "Обсудить решение",
      contactEyebrow: "Контакты",
      contactTitle: "Запрос и контакты",
      contactDescription: "Здесь можно разместить прямые контакты, форму запроса и будущие коммерческие заявки.",
      contactAction: "К форме",
    },
    site: {
      brandTagline: "Уличное освещение для глобальных проектов",
      stats: {
        yearsExperience: "Лет опыта",
        projectsServed: "Проектов",
        customization: "Кастомизация",
        certifiedSupply: "Сертифицированные поставки",
        warranty: "Гарантия",
      },
      why: {
        experience: {
          title: "15+ лет опыта в наружном освещении",
          description: "Стабильный процесс и опыт поставок для проектов.",
        },
        oem: {
          title: "Поддержка OEM & ODM",
          description: "Гибкая кастомизация бренда, конструкции и спецификаций.",
        },
        team: {
          title: "Профессиональная инженерная команда",
          description: "Быстрый ответ на технические вопросы и требования.",
        },
        quality: {
          title: "Строгий контроль качества",
          description: "Стабильные стандарты производства для долгой службы.",
        },
        cert: {
          title: "Сертификаты CE / RoHS / ISO",
          description: "Документы для соответствия требованиям мировых рынков.",
        },
        delivery: {
          title: "Быстрая поставка",
          description: "Эффективное производство и отправка под сроки проекта.",
        },
        global: {
          title: "Поддержка глобальных проектов",
          description: "Процесс работы для дистрибьюторов, подрядчиков и закупщиков.",
        },
        warranty: {
          title: "Гарантия 5 лет",
          description: "Уверенность в надёжности и обслуживании.",
        },
      },
    },
  },
};

type Locale = keyof typeof dictionaries;

type LanguageContextType = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => any;
};

const STORAGE_KEY = "zhuomei_locale";

const LanguageContext = createContext<LanguageContextType>({
  locale: "en",
  setLocale: () => {},
  t: (key: string) => key,
});

function getByPath(source: any, path: string) {
  return path.split(".").reduce((value, part) => (value ? value[part] : undefined), source);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");

  useEffect(() => {
    const stored = typeof window !== "undefined" ? (window.localStorage.getItem(STORAGE_KEY) as Locale | null) : null;
    if (stored && dictionaries[stored]) {
      setLocaleState(stored);
      document.documentElement.lang = stored;
    }
  }, []);

  const setLocale = (nextLocale: Locale) => {
    setLocaleState(nextLocale);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, nextLocale);
    }
    document.documentElement.lang = nextLocale;
  };

  const t = useMemo(() => {
    return (key: string) => getByPath(dictionaries[locale], key) ?? key;
  }, [locale]);

  return <LanguageContext.Provider value={{ locale, setLocale, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
